# Build options
[buildOptions]
optimizeWithTtx = false

# Building plans
[buildPlans.Iosevka2]
family = "Iosevka2"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

  [buildPlans.Iosevka2.variants]
  inherits = "ss14"

    [buildPlans.Iosevka2.variants.design]
    r = "hookless-serifless"
    t = "flat-hook-short-neck"
    lower-alpha = "crossing"
    zero = "slashed"
    seven = "straight-serifless-crossbar"

  [buildPlans.Iosevka2.ligations]
  inherits = "clike"

[buildPlans.Iosevka2.widths.Normal]
shape = 500
menu = 5
css = "normal"

[collectPlans.Iosevka2]
release = true
from = ["Iosevka2"]

###################################################################################################
# Weight mappings (style => shape weight, menu weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   Menu weight  : affects the font menu name
#   CSS weight   : affects the webfont CSS "font-weight" property
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 350, 400, 450, 500, 600, 700,
#             800, 900, and "shape" properly only supports number between 100 and 900 (inclusive).


[weights.Regular]
shape = 400
menu  = 400
css   = 400

[weights.Bold]
shape = 700
menu  = 700
css   = 700

# slope mappings (style => slope angle, shape slope grade, menu slope, CSS slope)
[slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[slopes.Oblique]
angle = 9.4
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

# Width mappings (style => shape width, menu width, CSS stretch)
#   Shape width   : affects the shape of the glyphs
#   Menu width    : affects the font menu name
#   CSS stretch   : affects the webfont CSS "font-stretch" property
#
# IMPORTANT : Currently "shape" property only support 3 ... 9
#              and "menu" only support 1 ... 9

[widths.Normal]
shape = 500
menu  = 5
css   = "normal"

